### ISSUE TITLE
The argument type 'WorkersScreen' can't be assigned to the parameter type 'Widget'.

### ISSUE THREAD

**Issue by marenovakovic** [Milad-Akarie/auto_route_library#1542]
On versions 6 and 7 of auto_route generated code contains following error:
`The argument type 'WorkersScreen' can't be assigned to the parameter type 'Widget'.`

```
part 'customer_router.gr.dart';

@AutoRouterConfig(replaceInRouteName: 'Route,Screen')
class CustomerRouter extends _$CustomerRouter {
  @override
  RouteType get defaultRouteType => RouteType.material();

  @override
  List<AutoRoute> get routes => [
        AutoRoute(page: WorkersScreen.page),
      ];
}
```
Inside generated code:
```
WorkersScreen.name: (routeData) {
      return AutoRoutePage<dynamic>(
        routeData: routeData,
        child: WorkersScreen(), // error is here
      );
    }

/// generated route for
/// [WorkersScreen]
class WorkersScreen extends PageRouteInfo<void> {
  const WorkersScreen({List<PageRouteInfo>? children})
      : super(
          WorkersScreen.name,
          initialChildren: children,
        );

  static const String name = 'WorkersScreen';

  static const PageInfo<void> page = PageInfo<void>(name);
}
```

**Comment by marenovakovic** [comment]
Resolved.

`import 'admin_router.gr.dart';`
instead of
`part 'admin_router.gr.dart';`

**Comment by aidanmack** [comment]
Hey can I just confirm that your router class now looks something like this?
```
@AutoRouterConfig()
class AppRouter {
  List<AutoRoute> get routes => [
        AutoRoute(page: InitRoute.page, initial: true),
        AutoRoute(page: SomeTestRoute.page),
      ];
}
```

To be honest I need to go away and understand the difference between import and part
also why we no longer extend from its self `class AppRouter extends _$AppRouter {`
Didnt really understand that to start with anyway.

**Comment by aidanmack** [comment]
Also when using import, how do you assign the routerconfig?

For example `routerConfig: _appRouter.config()` does not work

**Comment by yogithesymbian** [comment]
> Resolved.
> 
> `import 'router.gr.dart';` instead of `part 'router.gr.dart';`

i would like to clarity and more clarity here
using
```
import 'app_router.gr.dart';
```
instead of
```
part 'app_router.gr.dart';
```

**you should modify** `class AppRouter extends _$AppRouter {` into `class AppRouter extends $AppRouter {`

**i dont know why its solved me ,** 

and why the documentation is using `part` the errors is always appear like your question

```
➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-arm64, locale en-ID)
    • Flutter version 3.13.0 on channel stable at /Users/yogiarifwidodo/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (2 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/yogiarifwidodo/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/yogiarifwidodo/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Zulu11.48+21-CA (build 11.0.11+9-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • V2 PRO (mobile) • 192.168.43.9:5555 • android-arm    • Android 7.1.2 (API 25)
    • macOS (desktop) • macos             • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)    • chrome            • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
➜  ~
```
and 
```
environment:
  sdk: ">=2.17.6 <3.0.0"
....

in the documentation there is no explain for this case ...
auto_route: ^7.8.0
.....
.....
auto_route_generator: ^7.3.1
```

**Comment by sanchitmonga22** [comment]
It still does not work for me, I am following the official documentation on the website and I am getting the error in the auto-generated code that my Page can't be assigned to the parameter type "Widget" 

How were you able to solve it? I'd really appreciate your help. Thanks!

**Comment by sanchitmonga22** [comment]
Okay so I think I was able to fix it by removing the part and using import, and the steps that have been listed out by @yogithesymbian  above

**Comment by sanchitmonga22** [comment]
But this issue should be addressed as part of the following releases or the documentation needs to be updated.

**Comment by jon13doe** [comment]
Same issue. import 'router.gr.dart'; instead of part 'router.gr.dart'; plus class AppRouter extends _$AppRouter { into class AppRouter extends $AppRouter { work for me.

**Comment by dev-abir** [comment]
This is for anyone facing the same issue, just mentioning what I found after some experimentation.

Make your screens' class name end with `Screen`: like `BookListScreen`. The generator will create `BookListRoute`.

Now there's no confusion.
```dart
  @override
  final Map<String, PageFactory> pagesMap = {
    BookListRoute.name: (routeData) {
      return AutoRoutePage<dynamic>(
        routeData: routeData,
        // BookListScreen() should be your handwritten Screen not the generated route
        child: const BookListScreen(),
      );
    }
  };
```

If the generator creates a Route with the same name (`BookListScreen`) as of your own written Screen, then it creates a confusion. This is how the generated Route part should be (notice it changed my `BookListScreen` to `BookListRoute`):

```dart
/// generated route for
/// [BookListScreen]
class BookListRoute extends PageRouteInfo<void> {
  const BookListRoute({List<PageRouteInfo>? children})
      : super(
          BookListRoute.name,
          initialChildren: children,
        );

  static const String name = 'BookListRoute';

  static const PageInfo<void> page = PageInfo<void>(name);
}
```

Thus this is my routes listing file:
```dart
import 'package:auto_route/auto_route.dart';

// NOTE: whenever a new screen is added, re-generate the route file or watch
// for changes and import them here, it will be added to the part file as well
import 'package:.../screens/book_list_screen.dart';

part 'app_router.gr.dart';

@AutoRouterConfig()
class AppRouter extends _$AppRouter {
  @override
  List<AutoRoute> get routes => [
        /// routes go here
        AutoRoute(page: BookListRoute.page)
      ];
}
```

The code generation part might need some fixes, till then someone should add these pointers to the docs.

**Comment by Amrazyan** [comment]
> This is for anyone facing the same issue, just mentioning what I found after some experimentation.
> 
> Make your screens' class name end with `Screen`: like `BookListScreen`. The generator will create `BookListRoute`.
> 
> Now there's no confusion.
> 
> ```dart
>   @override
>   final Map<String, PageFactory> pagesMap = {
>     BookListRoute.name: (routeData) {
>       return AutoRoutePage<dynamic>(
>         routeData: routeData,
>         // BookListScreen() should be your handwritten Screen not the generated route
>         child: const BookListScreen(),
>       );
>     }
>   };
> ```
> 
> If the generator creates a Route with the same name (`BookListScreen`) as of your own written Screen, then it creates a confusion. This is how the generated Route part should be (notice it changed my `BookListScreen` to `BookListRoute`):
> 
> ```dart
> /// generated route for
> /// [BookListScreen]
> class BookListRoute extends PageRouteInfo<void> {
>   const BookListRoute({List<PageRouteInfo>? children})
>       : super(
>           BookListRoute.name,
>           initialChildren: children,
>         );
> 
>   static const String name = 'BookListRoute';
> 
>   static const PageInfo<void> page = PageInfo<void>(name);
> }
> ```
> 
> Thus this is my routes listing file:
> 
> ```dart
> import 'package:auto_route/auto_route.dart';
> 
> // NOTE: whenever a new screen is added, re-generate the route file or watch
> // for changes and import them here, it will be added to the part file as well
> import 'package:.../screens/book_list_screen.dart';
> 
> part 'app_router.gr.dart';
> 
> @AutoRouterConfig()
> class AppRouter extends _$AppRouter {
>   @override
>   List<AutoRoute> get routes => [
>         /// routes go here
>         AutoRoute(page: BookListRoute.page)
>       ];
> }
> ```
> 
> The code generation part might need some fixes, till then someone should add these pointers to the docs.

Thanks, it worked
