### ISSUE TITLE
Flutter 1.22 broke the library auto generation

### ISSUE THREAD

**Issue by JohnPinto** [Milad-Akarie/auto_route_library#250]
Since the 1.22 update the auto generation keeps stuck in the 
```
[WARNING] No actions completed for 15.1s, waiting on:
  - auto_route_generator:autoRouteGenerator on lib/pages/cumprimento/Widgets/anexos_modal.dart
  - auto_route_generator:autoRouteGenerator on lib/pages/cumprimento/Widgets/video_preview_midias.dart
  - auto_route_generator:autoRouteGenerator on lib/pages/cumprimento/Widgets/anexo_widget.dart
  - auto_route_generator:autoRouteGenerator on lib/pages/cumprimento/cumprimento_preview_dialog.dart
  - auto_route_generator:autoRouteGenerator on lib/pages/cumprimento/cumprimento_page.dart
  .. and 11 more
```

And in the beginning of the auto generation there is a severe error.

```
[SEVERE] auto_route_generator:autoRouteGenerator on lib/main.dart:

Bad state: Unexpected diagnostics:
/home/johnpinto/.local/share/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:152:17 - This requires the 'non-nullable' language feature to be enabled.
/home/johnpinto/.local/share/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:119:41 - This requires the 'non-nullable' language feature to be enabled.
/home/johnpinto/.local/share/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:133:32 - This requires the 'non-nullable' language feature to be enabled.
/home/johnpinto/.local/share/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:186:51 - This requires the 'non-nullable' language feature to be enabled.
/home/johnpinto/.local/share/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:88:62 - This requires the 'non-nullable' language feature to be enabled.
/home/johnpinto/.local/share/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:153:38 - This requires the 'non-nullable' language feature to be enabled.
/home/johnpinto/.local/share/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:64:4 - This requires the 'non-nullable' language feature to be enabled.
/home/johnpinto/.local/share/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:154:25 - This requires the 'non-nullable' language feature to be enabled.
/home/johnpinto/.local/share/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:18:17 - This requires the 'non-nullable' language feature to be enabled.
/home/johnpinto/.local/share/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:118:48 - This requires the 'non-nullable' language feature to be enabled.
/home/johnpinto/.local/share/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:132:37 - This requires the 'non-nullable' language feature to be enabled.
/home/johnpinto/.local/share/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:19:11 - This requires the 'non-nullable' language feature to be enabled.
/home/johnpinto/.local/share/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:159:38 - This requires the 'non-nullable' language feature to be enabled.
/home/johnpinto/.local/share/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:168:32 - This requires the 'non-nullable' language feature to be enabled.
/home/johnpinto/.local/share/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:47:14 - This requires the 'non-nullable' language feature to be enabled.
```

I really like this library and I would like it to keep it in my work project, but in the state that it is now, I have no choice but to switch to the default navigator for now. 

Edit: added the output from the debug console

```
Launching lib/main.dart on AOSP on IA Emulator in debug mode...
lib/main.dart:66:21: Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:mobile/src/router/router.gr.dart'.
            router: Router(),
                    ^^^^^^
lib/main.dart:65:38: Error: Inferred type argument 'dynamic' doesn't conform to the bound 'RouterBase' of the type variable 'T' on 'ExtendedNavigator<dynamic>.builder'.
 - 'RouterBase' is from 'package:auto_route/src/router_base.dart' ('../../../.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-0.6.7/lib/src/router_base.dart').
 - 'ExtendedNavigator' is from 'package:auto_route/src/extended_navigator.dart' ('../../../.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-0.6.7/lib/src/extended_navigator.dart').
Try specifying type arguments explicitly so that they conform to the bounds.
          builder: ExtendedNavigator.builder(
                                     ^
../../../.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-0.6.7/lib/src/extended_navigator.dart:24:36: Context: This is the type variable whose bound isn't conformed to.
  static TransitionBuilder builder<T extends RouterBase>({
                                   ^


FAILURE: Build failed with an exception.

* Where:
Script '/home/johnpinto/.local/share/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/johnpinto/.local/share/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```

Edit2: I was capable to make it work, the problem is that the new navigator 2.0 has a class with the same `Router` name on it, but the code generation is still borked.

**Comment by YoussefGheith** [comment]
For the naming problem we can  import 'app/router.gr.dart' as auto_router
and use it like this  "auto_router.Router().onGenerateRoute" 

but as you said the auto generate route is now broken  !!

**Comment by RodolfoSilva** [comment]
This issue appears in the `injectable` package made by @Milad-Akarie.

**Comment by harshitsangani** [comment]
@JohnPinto can you explain how you fixed the issue temporarily ?

**Comment by RodolfoSilva** [comment]
@harshitsangani, i've fixed my issue doing this:

First I've made downgrade of `build_runner` to `0.10.0`
And add the prefix indicate by @YoussefGheith, and the error goes away.
```dart
import 'app/router.gr.dart' as AutoRouter
```

**Comment by petrubocsanean** [comment]
Another way to fix this issue is to hide the Router when importing material.dart

Example:

`import 'package:flutter/material.dart' hide Router;`

**Comment by RodolfoSilva** [comment]
Nice @petrubocsanean 💯

**Comment by TarekkMA** [comment]
so I have found a solution for the code generation. The issue seems to be happening from the analyzer package. you can try to upgrade your packages or you can add this snippet to your pubspec.yaml file
```yaml
dependency_overrides:
  analyzer: '0.39.15'
```

**Comment by JohnPinto** [comment]
@TarekkMA comment basically fixed it, it works now, thx a lot!

Not sure if I should close the issue now, since the library is still not working out of the box yet.

**Comment by shahzans** [comment]
> @harshitsangani, i've fixed my issue doing this:
> 
> First I've made downgrade of `build_runner` to `0.10.0`
> And add the prefix indicate by @YoussefGheith, and the error goes away.
> 
> ```dart
> import 'app/router.gr.dart' as AutoRouter
> ```

**I'm getting the below error when downgrading the `build_runner` to `0.10.0`, could you please confirm, if it is `0.10.0` or `1.10.1`, thanks!**

`Because no versions of auto_route_generator match >0.6.8 <0.7.0 and auto_route_generator 0.6.8 depends on build_runner ^1.10.1, auto_route_generator ^0.6.8 requires build_runner ^1.10.1.`

**Comment by TarekkMA** [comment]
@shahzans keep you build_runner as is, rename `$Router` to be something like `$AutoRouter`, and add this to your pubspec.yaml
```
dependency_overrides:
  analyzer: '0.39.15'
``` 
and everything should get back to normal.

You also can avoid adding the ``dependency_overrides`` rule if you upgrade your packages or change versions since I didn't need this after I deleted my pubspec.lock and upgraded some packages.

**Comment by shahzans** [comment]
> @shahzans keep you build_runner as is, rename `$Router` to be something like `$AutoRouter`, and add this to your pubspec.yaml
> 
> ```
> dependency_overrides:
>   analyzer: '0.39.15'
> ```
> 
> and everything should get back to normal.
> 
> You also can avoid adding the `dependency_overrides` rule if you upgrade your packages or change versions since I didn't need this after I deleted my pubspec.lock and upgraded some packages.

Thanks @TarekkMA for your help!

**Comment by zs-dima** [comment]
dependency_overrides is not safe to use

**Comment by zs-dima** [comment]
> auto_route_generator 0.6.8 depends on analyzer ^0.39.14
> hive_generator ^0.8.1 requires analyzer >=0.40.0 <2.0.0

- issue still there

**Comment by TarekkMA** [comment]
> dependency_overrides is not safe to use

it's meant as a temporary solution, and in my project updating some of my  dependencies did solve the issue without the need for the `dependency_overrides`.

**Comment by Rayv1** [comment]
For me it seems that this package is no longer supported, as @Milad-Akarie is not active since about 2 months. The same Issue as with the injectable Package.

**Comment by zs-dima** [comment]
@Milad-Akarie very responsive so he will update library as soon as we will be able to

**Comment by SNPBharadwaj** [comment]
@Milad-Akarie Any update on this dear, our apps are nearing live date its heavily dependent on both of your packages auto_routing and injectable please can you update them, and least leave a tentative date

**Comment by Milad-Akarie** [comment]
Hello all. I apologize for disappearing for the last two months, my dad had very serious health issues and I could't get any work done. 
anyways, I'm here now and fixes will be pushed real soon. Thanks for your patience.

**Comment by Rayv1** [comment]
@Milad-Akarie I hope you are better now and you stay healthy.  
All of your Packages are stunning and for me they are"core" plugins for every app, 
its amazing to hear you!

**Comment by YoussefGheith** [comment]
طهورًا خوي ميلاد 
إن شاء الله لباس علي الوالد ربي يشفيه ويعافيه
تحياتي..

**Comment by TarekkMA** [comment]
ألف سلامة علي والدك. أتمني له الشفاء العاجل والصحة والسلامة إن شاء الله

**Comment by Milad-Akarie** [comment]
> طهورًا خوي ميلاد
> إن شاء الله لباس علي الوالد ربي يشفيه ويعافيه
> تحياتي..

الله لايوريك بأس خوي
ربي يحفظك

**Comment by Milad-Akarie** [comment]
> ألف سلامة علي والدك. أتمني له الشفاء العاجل والصحة والسلامة إن شاء الله

الله يسلمك، كنت عندكم في مصر

**Comment by Milad-Akarie** [comment]
This should be fixed in 

```yaml
auto_route: 0.6.9
auto_route_generator: 0.6.9
```
someone confirm that it works?

**Comment by zs-dima** [comment]
@Milad-Akarie thanks for looking into
`Because hive_generator >=0.8.0 depends on analyzer >=0.40.0 <2.0.0 and auto_route_generator >=0.6.9 depends on analyzer ^0.39.15, hive_generator >=0.8.0 is incompatible with auto_route_generator >=0.6.9.`
Issue still there

**Comment by Milad-Akarie** [comment]
I didn't pay attention to this one. 
try upgrading to 0.6.10
```yaml
auto_route_generator: 0.6.10

**Comment by SNPBharadwaj** [comment]
@Milad-Akarie thanks it is working now, can you help us by updating injectable aswell because these are our core dependencies

**Comment by theweiweiway** [comment]
sorry to hear that Milad. We appreciate everything you do for the Flutter community. Wish you and your family the best!

**Comment by JohnPinto** [comment]
Sorry to hear about your father @Milad-Akarie, I hope he gets better! Thank you for taking time in this tough moment to fix the library.

Best wishes from Brazil!

**Comment by RodolfoSilva** [comment]
> Hello all. I apologize for disappearing for the last two months, my dad had very serious health issues and I could't get any work done.
> anyways, I'm here now and fixes will be pushed real soon. Thanks for your patience.

I hope your father gets better! Will be alright!
