### ISSUE TITLE
Does not display URL path variables values

### ISSUE THREAD

**Issue by BartusZak** [Milad-Akarie/auto_route_library#440]
Hey,

I'm using `RouteGuards` with `router.root.push`:

```dart
      router.root.push(
          ResourcePaymentRoute(resource: 'audiobook', resourceId: audiobookId));
```

where `audiobookId` is a variable eg. `10`

It displays in a Google Chrome Url Tab like below:
`http://localhost:53992/#/payment/register/audiobook/audiobookId`

![image](https://user-images.githubusercontent.com/16143176/113000062-c7896600-916f-11eb-9f53-571a2eba45db.png)

but should be
`http://localhost:53992/#/payment/register/audiobook/10`

Widget gets correct value when I pass it (in that case `10`). 

<details>
<summary>ResourcePaymentPage</summary>

```dart
class ResourcePaymentPage extends StatefulWidget {
  final String resourceId;
  final String resource;

  static const path = '/payment/register/:resource/:resourceId';

  const ResourcePaymentPage(
      {Key key,
      @PathParam('resource') @required this.resource,
      @PathParam('resourceId') @required this.resourceId})
      : super(key: key);

  @override
  _ResourcePaymentPageState createState() => _ResourcePaymentPageState();
}
```
</details>

<details>
<summary>ResourcePaymentRoute</summary>

```dart
class ResourcePaymentRoute extends _i1.PageRouteInfo {
  ResourcePaymentRoute(
      {this.key, @_i2.required this.resource, @_i2.required this.resourceId})
      : super(name,
            path: '/payment/register/:resource/:resourceId',
            params: {'resource': resource, 'resourceId': resourceId});

  ResourcePaymentRoute.fromMatch(_i1.RouteMatch match)
      : key = null,
        resource = match.pathParams.getString('resource'),
        resourceId = match.pathParams.getString('resourceId'),
        super.fromMatch(match);

  final _i2.Key key;

  final String resource;

  final String resourceId;

  static const String name = 'ResourcePaymentRoute';
}
```
</details>

**Comment by Milad-Akarie** [comment]
@BartusZak I believe that was fixed in the new versions, you didn't migrate yet?

**Comment by BartusZak** [comment]
Hey @Milad-Akarie,

I just have migrated my project to `null-safety` and routing stoped working.
It includes Guards and redirections.

Is there any major change that routing does not work?

<details>
<summary> flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.3)
[√] Connected device (2 available)

• No issues found!
```
</details>

```
dependencies:   
 auto_route: ^1.0.2
...
dev_dependencies: 
  auto_route_generator: ^1.0.2
```

**Comment by BartusZak** [comment]
Catched one major change in `Dio` package which breaks my app work flow (`dio interceptors`).

**Comment by BartusZak** [comment]
@Milad-Akarie 
Problem still occurs even after update to `1.0.2`

![image](https://user-images.githubusercontent.com/16143176/113297303-bb7ddf80-92fa-11eb-8ae8-1faca7e88b45.png)

**Comment by Milad-Akarie** [comment]
@BartusZak I can not reproduce this, could you show me your router setup?

**Comment by Milad-Akarie** [comment]
@BartusZak everything looks fine, could you share the generated router?

**Comment by BartusZak** [comment]
@Milad-Akarie there you go:

<details>
<summary> AppRouter.gr.dart</summary>

```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// AutoRouteGenerator
// **************************************************************************

import 'package:auto_route/auto_route.dart' as _i1;
import 'package:flutter/material.dart' as _i23;

import '../../../../common/widgets/dialog/LoadingFulScreenDialog.dart' as _i8;
import '../../../audiobook/presentation/pages/AudiobookPage.dart' as _i10;
import '../../../document/presentation/pages/DocumentPage.dart' as _i12;
import '../../../login/presentation/pages/ForgotPasswordPage.dart' as _i20;
import '../../../login/presentation/pages/LoginPage.dart' as _i16;
import '../../../login/presentation/pages/ResetPasswordPage.dart' as _i21;
import '../../../multibook/presentation/pages/MultibookPage.dart' as _i9;
import '../../../payment/bloc/payment/payment_bloc.dart' as _i25;
import '../../../payment/presentation/pages/PaymentWebViewPage.dart' as _i15;
import '../../../payment/presentation/pages/ResourcePaymentPage.dart' as _i13;
import '../../../payment/presentation/pages/VerifyPaymentPage.dart' as _i14;
import '../../../room/presentation/pages/RoomPage.dart' as _i7;
import '../../../signUp/presentation/pages/EmailConfirmPage.dart' as _i19;
import '../../../signUp/presentation/pages/PhoneConfirmPage.dart' as _i18;
import '../../../signUp/presentation/pages/SignUpPage.dart' as _i17;
import '../../../task/data/classes/painter/PainterArguments.dart' as _i24;
import '../../../task/presentation/pages/painter/PainterWebPage.dart' as _i11;
import 'data/guards/AudiobookAccessGuard.dart' as _i5;
import 'data/guards/AuthGuard.dart' as _i3;
import 'data/guards/FetchMultibookPlaceholder.dart' as _i2;
import 'data/guards/LoggedGuard.dart' as _i6;
import 'data/guards/MultibookAccessGuard.dart' as _i4;
import 'presentation/pages/PageNotFound.dart' as _i22;

class AppRouter extends _i1.RootStackRouter {
  AppRouter(
      {required this.fetchMultibookPlaceholder,
      required this.authGuard,
      required this.multibookAccessGuard,
      required this.audiobookAccessGuard,
      required this.loggedGuard});

  final _i2.FetchMultibookPlaceholder fetchMultibookPlaceholder;

  final _i3.AuthGuard authGuard;

  final _i4.MultibookAccessGuard multibookAccessGuard;

  final _i5.AudiobookAccessGuard audiobookAccessGuard;

  final _i6.LoggedGuard loggedGuard;

  @override
  final Map<String, _i1.PageFactory> pagesMap = {
    RoomRoute.name: (entry) {
      var pathParams = entry.routeData.pathParams;
      var args = entry.routeData.argsAs<RoomRouteArgs>(
          orElse: () => RoomRouteArgs(roomId: pathParams.optString('roomId')));
      return _i1.MaterialPageX(
          entry: entry, child: _i7.RoomPage(roomId: args.roomId));
    },
    LoadingFulScreenDialog.name: (entry) {
      return _i1.MaterialPageX(
          entry: entry,
          child: _i8.LoadingFulScreenDialog(),
          fullscreenDialog: true);
    },
    MultibookRoute.name: (entry) {
      var pathParams = entry.routeData.pathParams;
      var args = entry.routeData.argsAs<MultibookRouteArgs>(
          orElse: () => MultibookRouteArgs(
              multibookId: pathParams.getString('multibookId')));
      return _i1.MaterialPageX(
          entry: entry,
          child: _i9.MultibookPage(multibookId: args.multibookId));
    },
    AudiobookRoute.name: (entry) {
      var pathParams = entry.routeData.pathParams;
      var args = entry.routeData.argsAs<AudiobookRouteArgs>(
          orElse: () => AudiobookRouteArgs(
              audiobookId: pathParams.getString('audiobookId')));
      return _i1.MaterialPageX(
          entry: entry,
          child:
              _i10.AudiobookPage(key: args.key, audiobookId: args.audiobookId));
    },
    PainterWebRoute.name: (entry) {
      var args = entry.routeData
          .argsAs<PainterWebRouteArgs>(orElse: () => PainterWebRouteArgs());
      return _i1.MaterialPageX(
          entry: entry,
          child: _i11.PainterWebPage(
              key: args.key, painterArguments: args.painterArguments));
    },
    DocumentRoute.name: (entry) {
      return _i1.MaterialPageX(entry: entry, child: _i12.DocumentPage());
    },
    ResourcePaymentRoute.name: (entry) {
      var pathParams = entry.routeData.pathParams;
      var args = entry.routeData.argsAs<ResourcePaymentRouteArgs>(
          orElse: () => ResourcePaymentRouteArgs(
              resource: pathParams.getString('resource'),
              resourceId: pathParams.getString('resourceId')));
      return _i1.MaterialPageX(
          entry: entry,
          child: _i13.ResourcePaymentPage(
              key: args.key,
              resource: args.resource,
              resourceId: args.resourceId));
    },
    VerifyPaymentRoute.name: (entry) {
      var pathParams = entry.routeData.pathParams;
      var args = entry.routeData.argsAs<VerifyPaymentRouteArgs>(
          orElse: () => VerifyPaymentRouteArgs(
              paymentId: pathParams.optString('paymentId')));
      return _i1.MaterialPageX(
          entry: entry,
          child:
              _i14.VerifyPaymentPage(key: args.key, paymentId: args.paymentId));
    },
    PaymentWebViewRoute.name: (entry) {
      var args = entry.routeData.argsAs<PaymentWebViewRouteArgs>();
      return _i1.MaterialPageX(
          entry: entry,
          child: _i15.PaymentWebViewPage(
              key: args.key,
              paymentId: args.paymentId,
              paymentUrl: args.paymentUrl,
              resourceId: args.resourceId,
              resource: args.resource));
    },
    LoginRoute.name: (entry) {
      var args = entry.routeData
          .argsAs<LoginRouteArgs>(orElse: () => LoginRouteArgs());
      return _i1.MaterialPageX(
          entry: entry,
          child:
              _i16.LoginPage(key: args.key, onLoginResult: args.onLoginResult));
    },
    SignUpRoute.name: (entry) {
      var args = entry.routeData
          .argsAs<SignUpRouteArgs>(orElse: () => SignUpRouteArgs());
      return _i1.MaterialPageX(
          entry: entry,
          child: _i17.SignUpPage(
              key: args.key, onLoginResult: args.onLoginResult));
    },
    PhoneConfirmRoute.name: (entry) {
      var args = entry.routeData.argsAs<PhoneConfirmRouteArgs>();
      return _i1.MaterialPageX(
          entry: entry,
          child: _i18.PhoneConfirmPage(
              key: args.key,
              email: args.email,
              sendCodeOnPageLoad: args.sendCodeOnPageLoad,
              onLoginResult: args.onLoginResult));
    },
    EmailConfirmRoute.name: (entry) {
      var args = entry.routeData.argsAs<EmailConfirmRouteArgs>();
      return _i1.MaterialPageX(
          entry: entry,
          child: _i19.EmailConfirmPage(
              key: args.key,
              email: args.email,
              onLoginResult: args.onLoginResult));
    },
    ForgotPasswordRoute.name: (entry) {
      return _i1.MaterialPageX(entry: entry, child: _i20.ForgotPasswordPage());
    },
    ResetPasswordRoute.name: (entry) {
      var args = entry.routeData.argsAs<ResetPasswordRouteArgs>(
          orElse: () => ResetPasswordRouteArgs());
      return _i1.MaterialPageX(
          entry: entry,
          child:
              _i21.ResetPasswordPage(key: args.key, username: args.username));
    },
    RouteNotFound.name: (entry) {
      return _i1.MaterialPageX(entry: entry, child: _i22.PageNotFound());
    }
  };

  @override
  List<_i1.RouteConfig> get routes => [
        _i1.RouteConfig('/#redirect',
            path: '/', redirectTo: '/rooms/main', fullMatch: true),
        _i1.RouteConfig(RoomRoute.name, path: '/rooms/:roomId'),
        _i1.RouteConfig(LoadingFulScreenDialog.name,
            path: '/loading-ful-screen-dialog'),
        _i1.RouteConfig(MultibookRoute.name,
            path: '/multibook/:multibookId',
            guards: [
              fetchMultibookPlaceholder,
              authGuard,
              multibookAccessGuard
            ]),
        _i1.RouteConfig(AudiobookRoute.name,
            path: '/audiobook/:audiobookId',
            guards: [authGuard, audiobookAccessGuard]),
        _i1.RouteConfig(PainterWebRoute.name, path: '/painter'),
        _i1.RouteConfig(DocumentRoute.name, path: '/about'),
        _i1.RouteConfig(ResourcePaymentRoute.name,
            path: '/payment/register/:resource/:resourceId'),
        _i1.RouteConfig(VerifyPaymentRoute.name,
            path: '/payment/verify/:paymentId', guards: [authGuard]),
        _i1.RouteConfig(PaymentWebViewRoute.name,
            path: '/payment/:paymentId/pay'),
        _i1.RouteConfig(LoginRoute.name, path: '/login', guards: [loggedGuard]),
        _i1.RouteConfig(SignUpRoute.name, path: '/signup'),
        _i1.RouteConfig(PhoneConfirmRoute.name,
            path: '/signup/confirm/phone', guards: [loggedGuard]),
        _i1.RouteConfig(EmailConfirmRoute.name,
            path: '/signup/confirm/email', guards: [loggedGuard]),
        _i1.RouteConfig(ForgotPasswordRoute.name,
            path: '/login/forgotPassword', guards: [loggedGuard]),
        _i1.RouteConfig(ResetPasswordRoute.name,
            path: '/resetPassword', guards: [loggedGuard]),
        _i1.RouteConfig(RouteNotFound.name, path: '*')
      ];
}

class RoomRoute extends _i1.PageRouteInfo<RoomRouteArgs> {
  RoomRoute({String? roomId})
      : super(name,
            path: '/rooms/:roomId',
            args: RoomRouteArgs(roomId: roomId),
            params: {'roomId': roomId});

  static const String name = 'RoomRoute';
}

class RoomRouteArgs {
  const RoomRouteArgs({this.roomId});

  final String? roomId;
}

class LoadingFulScreenDialog extends _i1.PageRouteInfo {
  const LoadingFulScreenDialog()
      : super(name, path: '/loading-ful-screen-dialog');

  static const String name = 'LoadingFulScreenDialog';
}

class MultibookRoute extends _i1.PageRouteInfo<MultibookRouteArgs> {
  MultibookRoute({required String multibookId})
      : super(name,
            path: '/multibook/:multibookId',
            args: MultibookRouteArgs(multibookId: multibookId),
            params: {'multibookId': multibookId});

  static const String name = 'MultibookRoute';
}

class MultibookRouteArgs {
  const MultibookRouteArgs({required this.multibookId});

  final String multibookId;
}

class AudiobookRoute extends _i1.PageRouteInfo<AudiobookRouteArgs> {
  AudiobookRoute({_i23.Key? key, required String audiobookId})
      : super(name,
            path: '/audiobook/:audiobookId',
            args: AudiobookRouteArgs(key: key, audiobookId: audiobookId),
            params: {'audiobookId': audiobookId});

  static const String name = 'AudiobookRoute';
}

class AudiobookRouteArgs {
  const AudiobookRouteArgs({this.key, required this.audiobookId});

  final _i23.Key? key;

  final String audiobookId;
}

class PainterWebRoute extends _i1.PageRouteInfo<PainterWebRouteArgs> {
  PainterWebRoute({_i23.Key? key, _i24.PainterArguments? painterArguments})
      : super(name,
            path: '/painter',
            args: PainterWebRouteArgs(
                key: key, painterArguments: painterArguments));

  static const String name = 'PainterWebRoute';
}

class PainterWebRouteArgs {
  const PainterWebRouteArgs({this.key, this.painterArguments});

  final _i23.Key? key;

  final _i24.PainterArguments? painterArguments;
}

class DocumentRoute extends _i1.PageRouteInfo {
  const DocumentRoute() : super(name, path: '/about');

  static const String name = 'DocumentRoute';
}

class ResourcePaymentRoute extends _i1.PageRouteInfo<ResourcePaymentRouteArgs> {
  ResourcePaymentRoute(
      {_i23.Key? key, required String resource, required String resourceId})
      : super(name,
            path: '/payment/register/:resource/:resourceId',
            args: ResourcePaymentRouteArgs(
                key: key, resource: resource, resourceId: resourceId),
            params: {'resource': resource, 'resourceId': resourceId});

  static const String name = 'ResourcePaymentRoute';
}

class ResourcePaymentRouteArgs {
  const ResourcePaymentRouteArgs(
      {this.key, required this.resource, required this.resourceId});

  final _i23.Key? key;

  final String resource;

  final String resourceId;
}

class VerifyPaymentRoute extends _i1.PageRouteInfo<VerifyPaymentRouteArgs> {
  VerifyPaymentRoute({_i23.Key? key, required String? paymentId})
      : super(name,
            path: '/payment/verify/:paymentId',
            args: VerifyPaymentRouteArgs(key: key, paymentId: paymentId),
            params: {'paymentId': paymentId});

  static const String name = 'VerifyPaymentRoute';
}

class VerifyPaymentRouteArgs {
  const VerifyPaymentRouteArgs({this.key, required this.paymentId});

  final _i23.Key? key;

  final String? paymentId;
}

class PaymentWebViewRoute extends _i1.PageRouteInfo<PaymentWebViewRouteArgs> {
  PaymentWebViewRoute(
      {_i23.Key? key,
      required String? paymentId,
      required String? paymentUrl,
      required String? resourceId,
      required _i25.Resource? resource})
      : super(name,
            path: '/payment/:paymentId/pay',
            args: PaymentWebViewRouteArgs(
                key: key,
                paymentId: paymentId,
                paymentUrl: paymentUrl,
                resourceId: resourceId,
                resource: resource),
            params: {'paymentId': paymentId});

  static const String name = 'PaymentWebViewRoute';
}

class PaymentWebViewRouteArgs {
  const PaymentWebViewRouteArgs(
      {this.key,
      required this.paymentId,
      required this.paymentUrl,
      required this.resourceId,
      required this.resource});

  final _i23.Key? key;

  final String? paymentId;

  final String? paymentUrl;

  final String? resourceId;

  final _i25.Resource? resource;
}

class LoginRoute extends _i1.PageRouteInfo<LoginRouteArgs> {
  LoginRoute({_i23.Key? key, void Function(bool)? onLoginResult})
      : super(name,
            path: '/login',
            args: LoginRouteArgs(key: key, onLoginResult: onLoginResult));

  static const String name = 'LoginRoute';
}

class LoginRouteArgs {
  const LoginRouteArgs({this.key, this.onLoginResult});

  final _i23.Key? key;

  final void Function(bool)? onLoginResult;
}

class SignUpRoute extends _i1.PageRouteInfo<SignUpRouteArgs> {
  SignUpRoute({_i23.Key? key, void Function(bool)? onLoginResult})
      : super(name,
            path: '/signup',
            args: SignUpRouteArgs(key: key, onLoginResult: onLoginResult));

  static const String name = 'SignUpRoute';
}

class SignUpRouteArgs {
  const SignUpRouteArgs({this.key, this.onLoginResult});

  final _i23.Key? key;

  final void Function(bool)? onLoginResult;
}

class PhoneConfirmRoute extends _i1.PageRouteInfo<PhoneConfirmRouteArgs> {
  PhoneConfirmRoute(
      {_i23.Key? key,
      required String? email,
      bool sendCodeOnPageLoad = false,
      void Function(bool)? onLoginResult})
      : super(name,
            path: '/signup/confirm/phone',
            args: PhoneConfirmRouteArgs(
                key: key,
                email: email,
                sendCodeOnPageLoad: sendCodeOnPageLoad,
                onLoginResult: onLoginResult));

  static const String name = 'PhoneConfirmRoute';
}

class PhoneConfirmRouteArgs {
  const PhoneConfirmRouteArgs(
      {this.key,
      required this.email,
      this.sendCodeOnPageLoad = false,
      this.onLoginResult});

  final _i23.Key? key;

  final String? email;

  final bool sendCodeOnPageLoad;

  final void Function(bool)? onLoginResult;
}

class EmailConfirmRoute extends _i1.PageRouteInfo<EmailConfirmRouteArgs> {
  EmailConfirmRoute(
      {_i23.Key? key,
      required String? email,
      void Function(bool)? onLoginResult})
      : super(name,
            path: '/signup/confirm/email',
            args: EmailConfirmRouteArgs(
                key: key, email: email, onLoginResult: onLoginResult));

  static const String name = 'EmailConfirmRoute';
}

class EmailConfirmRouteArgs {
  const EmailConfirmRouteArgs(
      {this.key, required this.email, this.onLoginResult});

  final _i23.Key? key;

  final String? email;

  final void Function(bool)? onLoginResult;
}

class ForgotPasswordRoute extends _i1.PageRouteInfo {
  const ForgotPasswordRoute() : super(name, path: '/login/forgotPassword');

  static const String name = 'ForgotPasswordRoute';
}

class ResetPasswordRoute extends _i1.PageRouteInfo<ResetPasswordRouteArgs> {
  ResetPasswordRoute({_i23.Key? key, String? username})
      : super(name,
            path: '/resetPassword',
            args: ResetPasswordRouteArgs(key: key, username: username));

  static const String name = 'ResetPasswordRoute';
}

class ResetPasswordRouteArgs {
  const ResetPasswordRouteArgs({this.key, this.username});

  final _i23.Key? key;

  final String? username;
}

class RouteNotFound extends _i1.PageRouteInfo {
  const RouteNotFound() : super(name, path: '*');

  static const String name = 'RouteNotFound';
}
```
</details>

**Comment by Milad-Akarie** [comment]
do you get the params if you `print(context.routeData.pathParams)`?

**Comment by BartusZak** [comment]
That's correct.

I added `print(context.routeData.pathParams)` into `Widget build()` of `ResourcePaymentPage.dart`

```
context.routeData.pathParams
{resource: audiobook, resourceId: Aniol_Stroz_2021_01}
```

**Comment by Milad-Akarie** [comment]
context.routeData.match?

**Comment by Milad-Akarie** [comment]
@BartusZak if you type in the full path does it take you to the right location?

**Comment by BartusZak** [comment]
`context.routeData.match` `/payment/register/audiobook/audiobookId`

It does take me to correct route.

The problem appears only when I user in app routing redirections like 

```dart
        AutoRouter.of(context)
                .navigate(AudiobookRoute(audiobookId: audiobook.audiobookId!));
```

Please take note that I am using Flutter WEB

**Comment by BartusZak** [comment]
Typeing url directly in URL tab returns
`context.routeData.match` `/payment/register/audiobook/Aniol_Stroz_2021_01`

**Comment by Milad-Akarie** [comment]
I'm not sure what's going on, could you create a simple sample App and invite me in?

**Comment by BartusZak** [comment]
I would love to help, but can not manage time for that right know.

I will get back to you when `Simple App` will be ready.
